### ISSUE TITLE
Pycurl issues with Wfuzz 2.2.9

### ISSUE THREAD

**Issue by javixeneize** [xmendez/wfuzz#71]
Hi

Im running Wfuzz 2.2.9 and i am having the following error when running the tool

Fatal exception: Minimum pycurl required version is 7.43.0

I have that version installed

If i downgrade it to 2.2.8, it works fine

Is this a known issue?

Thanks

**Comment by xmendez** [comment]
Hi, You need that minimum pycurl version with 2.2.9.Cheers On 18 Jan 2018 11:37 a.m., javixeneize <notifications@github.com> wrote:Hi
Im running Wfuzz 2.2.9 and i am having the following error when running the tool
Fatal exception: Minimum pycurl required version is 7.43.0
I have that version installed
If i downgrade it to 2.2.8, it works fine
Is this a known issue?
Thanks

**Comment by menzow** [comment]
@xmendez I hae the same problem.

```
********************************************************
* Wfuzz 2.2.9 - The Web Fuzzer                         *
********************************************************

Target: https://www.comodo.com/check.php?FUZZ=1
Total requests: 950

==================================================================
ID	Response   Lines      Word         Chars          Payload
==================================================================


Fatal exception: Minimum pycurl required version is 7.43.0
root@0cc3f9762fd1:/wfuzz# pip show pycurl
Name: pycurl
Version: 7.43.0.1
Summary: PycURL -- A Python Interface To The cURL library
Home-page: http://pycurl.io/
Author: Oleg Pudeyev
Author-email: oleg@bsdpower.com
License: LGPL/MIT
Location: /usr/local/lib/python2.7/site-packages

root@0cc3f9762fd1:/wfuzz# uname -a
Linux 0cc3f9762fd1 4.9.75-linuxkit-aufs #1 SMP Tue Jan 9 10:58:17 UTC 2018 x86_64 GNU/Linux
```

**Comment by digininja** [comment]
I'm seeing the same thing:

```
$ pip show pycurl
Name: pycurl
Version: 7.43.0.1
Summary: PycURL -- A Python Interface To The cURL library
Home-page: http://pycurl.io/
Author: Oleg Pudeyev
Author-email: oleg@bsdpower.com
License: LGPL/MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

```
********************************************************
* Wfuzz 2.2.9 - The Web Fuzzer                         *
********************************************************

Target: xxx/FUZZ
Total requests: 3038

==================================================================
ID      Response   Lines      Word         Chars          Payload
==================================================================


Fatal exception: Minimum pycurl required version is 7.43.0
```

I think the problem isn't pycurl but the underlying libcurl3 package. This is the error that triggers the version message:

```
Traceback (most recent call last):
  File "/opt/tools/web/wfuzz/src/wfuzz/fuzzobjects.py", line 382, in to_http_object
    return Request.to_pycurl_object(c, self._request)
  File "/opt/tools/web/wfuzz/src/wfuzz/externals/reqresp/Request.py", line 273, in to_pycurl_object
    c.setopt(pycurl.PATH_AS_IS, 1)
AttributeError: 'module' object has no attribute 'PATH_AS_IS'
```

Looking at this check in in pycurl:

https://github.com/pycurl/pycurl/commit/aa89c8454bee6f695ff849ea2ab085eec4c915ce

PATH_AS_IS is only enabled if the underlying libcurl version is greater than 7.42:

```
+#if LIBCURL_VERSION_NUM >= MAKE_LIBCURL_VERSION(7, 42, 0)
```

On Debian Jessie, the version is only 7.38:

```
$ apt-cache show libcurl3
Package: libcurl3
Source: curl
Version: 7.38.0-4+deb8u8
Installed-Size: 547
```

Running this on Ubuntu Artful it works fine with pycurl 7.43.0, a lower version than on my Debian box.
